# Docker Compose Override - Longpolling and Worker Scaling
# This file extends docker-compose.yml with additional settings

services:
  odoo:
    environment:
      WORKERS: "8"
    command:
      [
        "odoo",
        "-c", "/etc/odoo/odoo.conf",
        "--proxy-mode",
        "--db-filter=^%d$$",
        "--workers=8",
        "--longpolling-port=8072"
      ]
    expose:
      - "8069"
      - "8072"

  # admin_workers is configured for scaling
  # The container_name is removed here to allow multiple instances
  # Use: docker compose up -d --scale admin_workers=5

  nginx:
    volumes:
      - ./config/nginx/site.longpoll.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/snippets:/etc/nginx/snippets:ro
      - ./config/nginx/.admin_htpasswd:/etc/nginx/.admin_htpasswd:ro
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot