version: "3.9"

services:
  odoo:
    environment:
      WORKERS: "8"
    command:
      [
        "odoo",
        "-c", "/etc/odoo/odoo.conf",
        "--proxy-mode",
        "--db-filter=^%d$$",
        "--workers=8",
        "--longpolling-port=8072"
      ]
    expose:
      - "8069"
      - "8072"

  admin_workers:
    command: ["rq", "worker", "-u", "${REDIS_URL}", "odoo_admin_jobs"]

  nginx:
    volumes:
      - ./config/nginx/site.longpoll.conf:/etc/nginx/conf.d/default.conf:ro
