apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo-saas
data:
  odoo.conf: |
    [options]
    admin_passwd = changeme_master
    db_host = $(PG_HOST)
    db_port = $(PG_PORT)
    db_user = $(PG_USER)
    db_password = $(PG_PASSWORD)
    addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
    logfile = /var/lib/odoo/odoo.log
    dbfilter = ^%d$
    proxy_mode = True
    limit_time_cpu = 120
    limit_time_real = 240
