---
# Source:
# https://cert-manager.io/docs/configuration/acme/#configuring-a-clusterissuer
# Replace the email address with your own.
# You can use the staging server for testing, but remember to switch to
# the production server for real certificates.
# Also ensure your Ingress controller can handle the HTTP-01 challenge.
# This example assumes the nginx Ingress controller; see your controller's
# documentation for details.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: admin@odoo.example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
