apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: odoo-saas
spec:
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  clusterIP: None  # headless for StatefulSet stable DNS
