apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: odoo-saas
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: PG_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: PG_PASSWORD } }
            - name: POSTGRES_DB
              value: "postgres"
          ports:
            - containerPort: 5432
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1",    memory: "2Gi" }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: data
          livenessProbe:
            exec:
              command: ["sh","-lc","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["sh","-lc","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
